# Generated by Django 2.2.8 on 2020-03-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
