# Generated by Django 2.2.8 on 2020-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout_page', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('modelPath', models.CharField(max_length=100)),
                ('repeats', models.IntegerField()),
            ],
        ),
    ]
