# Generated by Django 2.2.8 on 2020-04-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_page', '0003_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='description',
            new_name='exercise_desc',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='modelPath',
            new_name='exercise_name',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='name',
            new_name='model_path',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='repeats',
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=100)),
                ('exercise_num', models.IntegerField()),
                ('numRepeats', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_page.Exercise')),
            ],
        ),
    ]
