# Generated by Django 2.2.8 on 2020-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_page', '0004_auto_20200402_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='restTime',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workout',
            name='numRepeats',
            field=models.IntegerField(default=10),
        ),
    ]
