# Generated by Django 2.2.8 on 2020-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_page', '0005_auto_20200402_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='isTabata',
            field=models.BooleanField(default=False),
        ),
    ]
