# Generated by Django 2.2.8 on 2020-04-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_page', '0006_workout_istabata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workout',
            new_name='Workouts',
        ),
    ]
